// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Tm5saaHCj6lx-PnLF6NJa6IC2LVD5IQ',
    appId: '1:354643909125:web:2a62a8191149ff0f5cda6c',
    messagingSenderId: '354643909125',
    projectId: 'garfianto-portofolio',
    authDomain: 'garfianto-portofolio.firebaseapp.com',
    storageBucket: 'garfianto-portofolio.appspot.com',
    measurementId: 'G-SVYT4TVT0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoxca52nwGPgr1BtX_d1WTIHcZrT88S4g',
    appId: '1:354643909125:android:b04c9a31f1ac245c5cda6c',
    messagingSenderId: '354643909125',
    projectId: 'garfianto-portofolio',
    storageBucket: 'garfianto-portofolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApA6kGP2C-LsRZbtCjsTuCf3WJZ2KtBeM',
    appId: '1:354643909125:ios:64bad930a10337d95cda6c',
    messagingSenderId: '354643909125',
    projectId: 'garfianto-portofolio',
    storageBucket: 'garfianto-portofolio.appspot.com',
    iosBundleId: 'com.fian.riverpod',
  );
}
